name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Check the build
        run: pnpm run check

      # - name: Code linting
      #   run: pnpm run lint

      - name: Check dependencies, unused code
        run: pnpm run knip
